apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}  
spec:
  selector:
    app: nginx-v1
  ports:
  - port: 80
    targetPort: 80
  type: Loadbalancer
  # externalTrafficPolicy: Local
